export const ROUTES = {
  DEMO: '/demo',
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  USER: '/user',
  ADMIN: '/admin',
  PRODUCT: '/admin/product',
  PRODUCTS: '/admin/products',
  CATEGORY: '/admin/category',
  SUB_CATEGORY: '/admin/sub',
  COUPON: '/admin/coupon',
  HISTORY: '/user/history',
  PASSWORD: '/user/password',
  FORGOT_PASSWORD: '/forgotPassword',
  RESET_PASSWORD: '/reset-password/:token',
  WISHLIST: '/user/wishlist',
} as const;
